swagger: "2.0"
info:
  version: "0.0.1"
  title: Usuarios Api Rest
# Puerto donde se va a ejecutar el api rest
host: localhost:10010
# basePath contiene la ruta de los recursos
basePath: / 
schemes:
  - http
  - https
# formato del cuerpo que un cliente puede enviar (Content-Type)
consumes:
  - application/json
# formato de las respuestas del cliente(Accepts)
produces:
  - application/json
paths:
  /usuario:
    # nombre de nuestro controlador
    x-swagger-router-controller: usuario
    get:
      operationId: getAll
      description: contiene la lista de todos los usuarios
      # definimos el tipo de respuesta para Success "200" y Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUsuariosListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: save
      description: agrega un nuevo usuario a la lista
      # informacion del usuario a ser almacenada
      parameters:
        - name: titulo
          description: Propiedades de un usuario
          in: body
          required: true
          schema:
            $ref: "#/definitions/Usuarios"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /usuario/{id}:
    # nombre de nuestro controlador
    x-swagger-router-controller: usuario
    get:
      operationId: getOne
      description: obtiene un usuario a partir del parametro recibido
      # define el tipo de respuesta para Success "200" y Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUsuariosResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      operationId: update
      description: actualizamos datos de un usuario 
      # definimos los parametros
      parameters:
        - name: id
          description: id del Usuario
          type: string
          in: path
          required: true
        - name: title
          description: propiedades del Usuario
          in: body
          required: true
          schema:
            $ref: "#/definitions/Usuarios"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      operationId: remove
      description: eliminar un usuario
      # definiendo los parametros
      parameters:
        - name: id
          description: id del usuario
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# definicion del esquema
definitions:
  GetUsuariosListResponse:
    required:
      - usuarios
    properties:
      # Array de los usuarios existentes
      usuarios:
        type: array
        items: 
          type: object
          properties:
            id:
              type: string
            user:
              type: string
            pass:
              type: string
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: retorna 1 si es correcto
      description:
        type: string
        description: comentario 
    required:
      - success
      - description
  GetUsuariosResponse:
    required:
      - id
      - user
      - pass
    properties:
      id:
        type: string
      user: 
        type: string
      pass:
        type: string
  Usuarios:
    type: object
    properties:
      user:
        type: string
        description: nombre del usuario
      pass:
        type: string
        description: contraseña del usuario
    required:
      - user
      - pass
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string